"""Base strategy class and signal definitions.

All trading strategies inherit from BaseStrategy and implement
the `generate_signals()` method. Signals are standardized into
a common format for the execution engine.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any

import pandas as pd

from src.utils.logger import get_logger

logger = get_logger(__name__)


class SignalType(str, Enum):
    """Trading signal types."""
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


class SignalStrength(str, Enum):
    """Signal confidence levels."""
    STRONG = "strong"
    MODERATE = "moderate"
    WEAK = "weak"


class TradingStyle(str, Enum):
    """Trading style / holding period classification."""
    SCALPING = "scalping"          # 1-5 min charts, seconds to minutes
    SHORT_TERM = "short_term"      # 5-15 min charts, minutes to hours
    SWING = "swing"                # 1H-1D charts, hours to days
    POSITIONAL = "positional"      # 1D-1W charts, days to weeks


@dataclass
class Signal:
    """A trading signal generated by a strategy."""

    timestamp: datetime
    symbol: str
    signal_type: SignalType
    strength: SignalStrength = SignalStrength.MODERATE
    trading_style: TradingStyle = TradingStyle.SHORT_TERM
    price: float | None = None
    stop_loss: float | None = None
    target: float | None = None
    strategy_name: str = ""
    holding_period_minutes: int | None = None
    metadata: dict[str, Any] = field(default_factory=dict)

    @property
    def is_actionable(self) -> bool:
        """A signal is actionable if it's BUY or SELL (not HOLD)."""
        return self.signal_type in (SignalType.BUY, SignalType.SELL)

    def to_dict(self) -> dict[str, Any]:
        return {
            "timestamp": self.timestamp,
            "symbol": self.symbol,
            "signal_type": self.signal_type.value,
            "strength": self.strength.value,
            "trading_style": self.trading_style.value,
            "price": self.price,
            "stop_loss": self.stop_loss,
            "target": self.target,
            "strategy_name": self.strategy_name,
            "holding_period_minutes": self.holding_period_minutes,
            "metadata": self.metadata,
        }


@dataclass
class BacktestTrade:
    """A single trade executed during a backtest."""

    entry_time: datetime
    exit_time: datetime | None = None
    symbol: str = ""
    side: str = ""  # BUY or SELL
    entry_price: float = 0.0
    exit_price: float | None = None
    quantity: int = 1
    pnl: float = 0.0
    pnl_pct: float = 0.0
    stop_loss: float | None = None
    target: float | None = None
    exit_reason: str = ""  # "target", "stop_loss", "signal", "eod"

    @property
    def is_winner(self) -> bool:
        return self.pnl > 0

    @property
    def is_open(self) -> bool:
        return self.exit_time is None


@dataclass
class BacktestResult:
    """Aggregated results from a strategy backtest."""

    strategy_name: str
    symbol: str
    start_date: datetime
    end_date: datetime
    initial_capital: float
    final_capital: float
    trades: list[BacktestTrade] = field(default_factory=list)

    @property
    def total_trades(self) -> int:
        return len(self.trades)

    @property
    def winning_trades(self) -> int:
        return sum(1 for t in self.trades if t.is_winner)

    @property
    def losing_trades(self) -> int:
        return sum(1 for t in self.trades if not t.is_winner and not t.is_open)

    @property
    def win_rate(self) -> float:
        closed = self.total_trades - sum(1 for t in self.trades if t.is_open)
        if closed == 0:
            return 0.0
        return self.winning_trades / closed * 100

    @property
    def total_pnl(self) -> float:
        return sum(t.pnl for t in self.trades)

    @property
    def total_return_pct(self) -> float:
        if self.initial_capital == 0:
            return 0.0
        return (self.final_capital - self.initial_capital) / self.initial_capital * 100

    @property
    def max_drawdown(self) -> float:
        """Calculate maximum drawdown from the equity curve."""
        if not self.trades:
            return 0.0
        equity = self.initial_capital
        peak = equity
        max_dd = 0.0
        for trade in self.trades:
            equity += trade.pnl
            peak = max(peak, equity)
            dd = (peak - equity) / peak * 100 if peak > 0 else 0
            max_dd = max(max_dd, dd)
        return max_dd

    @property
    def profit_factor(self) -> float:
        """Gross profits / gross losses."""
        gross_profit = sum(t.pnl for t in self.trades if t.pnl > 0)
        gross_loss = abs(sum(t.pnl for t in self.trades if t.pnl < 0))
        if gross_loss == 0:
            return float("inf") if gross_profit > 0 else 0.0
        return gross_profit / gross_loss

    @property
    def avg_win(self) -> float:
        wins = [t.pnl for t in self.trades if t.is_winner]
        return sum(wins) / len(wins) if wins else 0.0

    @property
    def avg_loss(self) -> float:
        losses = [t.pnl for t in self.trades if not t.is_winner and not t.is_open]
        return sum(losses) / len(losses) if losses else 0.0

    def summary(self) -> dict[str, Any]:
        return {
            "strategy": self.strategy_name,
            "symbol": self.symbol,
            "total_trades": self.total_trades,
            "win_rate": round(self.win_rate, 1),
            "total_pnl": round(self.total_pnl, 2),
            "total_return_pct": round(self.total_return_pct, 2),
            "max_drawdown_pct": round(self.max_drawdown, 2),
            "profit_factor": round(self.profit_factor, 2),
            "avg_win": round(self.avg_win, 2),
            "avg_loss": round(self.avg_loss, 2),
        }


class BaseStrategy(ABC):
    """Abstract base class for all trading strategies.

    Subclasses must implement `generate_signals()`.
    """

    name: str = "BaseStrategy"
    trading_style: TradingStyle = TradingStyle.SHORT_TERM

    def __init__(self, config: dict[str, Any] | None = None) -> None:
        self.config = config or {}

    @abstractmethod
    def generate_signals(self, data: pd.DataFrame) -> list[Signal]:
        """Generate trading signals from market data.

        Args:
            data: DataFrame with at minimum: timestamp, open, high, low, close, volume.

        Returns:
            List of Signal objects.
        """
        ...

    def __repr__(self) -> str:
        return f"<{self.__class__.__name__}>"
